---
- hosts: build
  vars:
    go_tarball: go1.7.3.linux-amd64.tar.gz
    go_tarball_checksum: sha256:508028aac0654e993564b6e2014bf2d4a9751e3b286661b0b0040046cf18028e
    go_version_target: go version go1.7.3 linux/amd64
    set_go_path: true
    go_download_location: "https://storage.googleapis.com/golang/{{ go_tarball }}"

  roles:
    - golang
#    - docker

#  tasks:
#    - name: Get kubernetes source
#      command: go get k8s.io/kubernetes
  
